add_newline = false

[aws]
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[cmd_duration]
min_time = 500  # milliseconds
prefix = "â³ "

[git_branch]
symbol = "ğŸŒµ "

[git_commit]
disabled = false
prefix = "ğŸ”— "
suffix = " "

[kubernetes]
symbol = "â›µ "
style = "dimmed green"
disabled = false
